insert into exchange_value (id,from_currency,to_currency,conversion_multiple)
values(10001,'USD','INR','65')
insert into exchange_value (id,from_currency,to_currency,conversion_multiple)
values(10002,'ASD','INR','23')
insert into exchange_value (id,from_currency,to_currency,conversion_multiple)
values(10003,'EUR','INR','70')